export const accessServices: Record<string, string[]> = {
  "Logo, Design & Medien": [
    "Smashing Logo",
    "Canva",
    "Figma",
    "Adobe Creative Cloud",
    "Adobe Express",
    "Looka",
    "Brandmark",
    "Tailor Brands",
    "Logo.com",
    "Freepik",
    "Envato",
    "Shutterstock",
    "Artlist",
    "Unsplash",
  ],
  "Code, Deployment & Datenbanken": [
    "GitHub",
    "GitLab",
    "Bitbucket",
    "Vercel",
    "Netlify",
    "Supabase",
    "Firebase",
    "Cloudflare",
    "Render",
    "Railway",
    "DigitalOcean",
    "AWS",
    "Microsoft Azure",
    "Google Cloud",
    "Hetzner",
    "Docker Hub",
    "Neon",
    "MongoDB Atlas",
    "PlanetScale",
    "Upstash",
  ],
  "Domains, Hosting & Webseiten": [
    "IONOS",
    "STRATO",
    "ALL-INKL",
    "Hostinger",
    "GoDaddy",
    "Namecheap",
    "INWX",
    "DomainFactory",
    "Mittwald",
    "Manitu",
    "netcup",
    "World4You",
    "easyname",
    "dogado",
    "Host Europe",
    "Squarespace Domains",
    "WordPress",
    "Webflow",
    "Wix",
    "Squarespace",
    "Framer",
    "Shopify",
    "WooCommerce",
    "Shopware",
  ],
  "Google & Analyse": [
    "Google-Konto",
    "Google Workspace",
    "Gmail",
    "Google Analytics",
    "Google Tag Manager",
    "Google Search Console",
    "Google Ads",
    "Google Business Profile",
    "YouTube",
    "Looker Studio",
    "Google Merchant Center",
  ],
  "Meta & soziale Medien": [
    "Meta Business Suite",
    "Meta Business Manager",
    "Meta Ads",
    "Facebook",
    "Instagram",
    "WhatsApp Business",
    "WhatsApp Business Platform",
    "LinkedIn",
    "TikTok",
    "Pinterest",
    "X",
    "Threads",
    "Snapchat",
  ],
  "E-Mail & Versand": [
    "Microsoft 365",
    "Outlook",
    "Exchange",
    "Zoho Mail",
    "Proton Mail",
    "Resend",
    "Brevo",
    "Mailchimp",
    "SendGrid",
    "Mailgun",
    "Postmark",
    "Amazon SES",
    "MailerLite",
    "ActiveCampaign",
    "Klaviyo",
    "SMTP / E-Mail-Postfach",
  ],
  "KI & Automatisierung": [
    "OpenAI",
    "ChatGPT",
    "Anthropic / Claude",
    "Google AI Studio",
    "Gemini",
    "Perplexity",
    "Midjourney",
    "Runway",
    "ElevenLabs",
    "Make",
    "Zapier",
    "n8n",
    "Airtable",
    "Notion",
  ],
  "Zusammenarbeit & Support": [
    "Slack",
    "Microsoft Teams",
    "Zoom",
    "Discord",
    "Trello",
    "Asana",
    "ClickUp",
    "Monday.com",
    "Jira",
    "Linear",
    "Confluence",
    "Miro",
    "Dropbox",
    "Box",
    "Calendly",
    "Cal.com",
    "Typeform",
    "Tally",
    "Intercom",
    "Zendesk",
    "Freshdesk",
  ],
  "CRM, Abrechnung & Zahlungen": [
    "HubSpot",
    "Salesforce",
    "Pipedrive",
    "Zoho CRM",
    "Stripe",
    "PayPal",
    "Mollie",
    "Klarna",
    "Lexware Office",
    "sevdesk",
    "DATEV",
    "Bexio",
    "Xero",
    "QuickBooks",
    "Billbee",
    "FastBill",
  ],
  "Sicherheit & Monitoring": [
    "1Password",
    "Bitwarden",
    "Dashlane",
    "LastPass",
    "Sentry",
    "Better Stack",
    "UptimeRobot",
    "Uptime Kuma",
    "Cookiebot",
    "Usercentrics",
    "Borlabs Cookie",
    "Google reCAPTCHA",
    "Cloudflare Turnstile",
  ],
};
export const hostingProviders = [
  "IONOS",
  "STRATO",
  "ALL-INKL",
  "Hetzner",
  "netcup",
  "Hostinger",
  "GoDaddy",
  "Namecheap",
  "INWX",
  "DomainFactory",
  "Mittwald",
  "Manitu",
  "World4You",
  "easyname",
  "dogado",
  "Host Europe",
  "Cloudflare",
  "Vercel",
  "Netlify",
  "AWS",
  "Google Cloud",
  "Microsoft Azure",
  "DigitalOcean",
  "Shopify",
  "Webflow",
  "Wix",
  "Squarespace",
  "Framer",
];
export const mailProviders = [
  "Google Workspace",
  "Microsoft 365",
  "Exchange",
  "IONOS",
  "STRATO",
  "ALL-INKL",
  "Hetzner",
  "World4You",
  "easyname",
  "Zoho Mail",
  "Proton Mail",
  "Resend",
  "Brevo",
  "Mailchimp",
  "SendGrid",
  "Mailgun",
  "Postmark",
  "Amazon SES",
  "MailerLite",
  "Klaviyo",
  "Eigener SMTP-Server",
];
export const twoFactorOptions = [
  "Unbekannt",
  "Nicht erforderlich",
  "Authenticator-App",
  "SMS",
  "E-Mail-Code",
  "Sicherheitsschlüssel / Passkey",
  "Freigabe in App",
  "Freigabe durch Kunden",
  "Andere Methode",
] as const;
export const approvalOptions = [
  "Unbekannt",
  "Keine Freigabe nötig",
  "Kundenfreigabe nötig",
  "E-Mail-Postfachfreigabe nötig",
  "Kunden- und Postfachfreigabe nötig",
  "Freigabe bereits erteilt",
] as const;
export type AccessEntry = {
  id: string;
  customer_id: string;
  service: string;
  label: string;
  login_url: string;
  username: string;
  two_factor: string;
  approval: string;
  notes: string;
  updated_at: string;
};
export type InfrastructureEntry = {
  id: string;
  customer_id: string;
  domain: string;
  registrar: string;
  dns_provider: string;
  hosting_provider: string;
  email_provider: string;
  sending_provider: string;
  from_name: string;
  from_email: string;
  reply_to_email: string;
  smtp_host: string;
  smtp_port: number | null;
  smtp_security: string;
  credential_id: string | null;
  notes: string;
};
